[server]
hostname = "is.wso2" # TODO Replace with a parameter taken from the user
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin" # TODO Replace with a parameter taken from the user
password = "admin" # TODO Replace with a parameter taken from the user
create_admin_account = true

[transport.https.properties]
proxyPort="443"

[user_store]
type = "database_unique_id"

[database.identity_db]
url = "jdbc:sqlserver://sql-wso2-is-marketplace.database.windows.net:1433;database=WSO2IDENTITY_DB"
username = "dbserveradmin"
password = "hJuI78ShWq"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"

[database.shared_db]
url = "jdbc:sqlserver://sql-wso2-is-marketplace.database.windows.net:1433;database=WSO2SHARED_DB"
username = "dbserveradmin"
password = "hJuI78ShWq"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"

[database.user]
url = "jdbc:sqlserver://sql-wso2-is-marketplace.database.windows.net:1433;database=WSO2USER_DB"
username = "dbserveradmin"
password = "hJuI78ShWq"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"

[realm_manager]
data_source = "WSO2USER_DB"

[keystore.primary]
file_name = "keystore.p12"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"
type="PKCS12"

[truststore]
file_name="client-truststore.p12"
password="wso2carbon"
type="PKCS12"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

[clustering]
membership_scheme = "wka"
local_member_host = "10.2.0.7"
local_member_port = "4000"
members = ["10.2.0.7:4000", "10.2.0.4:4000"]

hazelcast.shutdownhook.enabled = "false"
hazelcast.logging.type = "log4j2"
