
packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 1"
    }
  }
}

source "azure-arm" "autogenerated_1" {
  tenant_id                              = var.azure_tenant_id
  subscription_id                        = var.azure_subscription_id
  build_resource_group_name              = var.resource_group
  client_id                              = var.azure_client_id
  client_secret                          = var.azure_client_secret
  image_offer                            = "0001-com-ubuntu-server-jammy"
  image_publisher                        = "Canonical"
  image_sku                              = "22_04-lts-gen2"
  os_type                                = "Linux"
  polling_duration_timeout               = "0h30m0s"
  private_virtual_network_with_public_ip = true
  temp_compute_name                      = "vm-wso2-identity-server"
  vm_size                                = "Standard_D4s_v3"
  shared_image_gallery_destination {
    subscription          = var.azure_subscription_id
    resource_group        = var.resource_group
    gallery_name          = var.sig_gallery_name
    image_name            = var.sig_image_name
    image_version         = var.sig_image_version
    storage_account_type  = "Standard_LRS"
    target_region {
      name = var.location
    }
  }
  managed_image_name                     = "isazuremarketplaceimage"
  managed_image_resource_group_name      = var.resource_group
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    script          = "install-wso2-is.sh"
  }
}

# source "azure-arm" "autogenerated_1" {
#   azure_tags = {
#     dept = "Engineering"
#     task = "Image deployment"
#   }
#   client_id                         = var.azure_client_id
#   client_secret                     = var.azure_client_secret
#   image_publisher                   = "Canonical"
#   image_offer                       = "0001-com-ubuntu-server-jammy"
#   image_sku                         = "22_04-lts"
#   location                          = "East US2"
#   managed_image_name                = "myPackerImage"
#   managed_image_resource_group_name = var.resource_group
#   os_type                           = "Linux"
#   subscription_id                   = var.azure_subscription_id
#   tenant_id                         = var.azure_tenant_id
#   vm_size                           = "Standard_DS2_v2"
#   shared_image_gallery_destination {
#     gallery_name        = var.sig_gallery_name
#     image_name          = var.sig_image_name
#     image_version       = var.sig_image_version
#     replication_regions = [var.location]
#     resource_group      = var.resource_group
#     subscription        = var.azure_subscription_id
#   }
# }

# build {
#   sources = ["source.azure-arm.autogenerated_1"]

#   provisioner "shell" {
#     execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
#     inline          = ["apt-get update", "apt-get upgrade -y", "apt-get -y install nginx", "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"]
#     inline_shebang  = "/bin/sh -x"
#   }

# }