#!/bin/bash

IS_DB_SCRIPTS_PATH=$1
SQL_SERVER_NAME=$2
SQL_SERVER_ADMIN_USERNAME=$3
SQL_SERVER_ADMIN_PASSWORD=$4

IDENTITY_DATABASE_NAME="WSO2IDENTITY_DB"
SHARED_DATABASE_NAME="WSO2SHARED_DB"
USER_DATABASE_NAME="WSO2USER_DB"

IDENTITY_DB_SETUP_SCRIPT="${IS_DB_SCRIPTS_PATH}/identity/mssql.sql"
CONSENT_DB_SETUP_SCRIPT="${IS_DB_SCRIPTS_PATH}/consent/mssql.sql"

SHARED_DB_SETUP_SCRIPT="${IS_DB_SCRIPTS_PATH}/mssql.sql"

USER_DB_SETUP_SCRIPT="${IS_DB_SCRIPTS_PATH}/mssql.sql"

sqlcmd -S "$SQL_SERVER_NAME" -U "$SQL_SERVER_ADMIN_USERNAME" -P "$SQL_SERVER_ADMIN_PASSWORD" -d "$IDENTITY_DATABASE_NAME" -i "$IDENTITY_DB_SETUP_SCRIPT"
sqlcmd -S "$SQL_SERVER_NAME" -U "$SQL_SERVER_ADMIN_USERNAME" -P "$SQL_SERVER_ADMIN_PASSWORD" -d "$IDENTITY_DATABASE_NAME" -i "$CONSENT_DB_SETUP_SCRIPT"

sqlcmd -S "$SQL_SERVER_NAME" -U "$SQL_SERVER_ADMIN_USERNAME" -P "$SQL_SERVER_ADMIN_PASSWORD" -d "$SHARED_DATABASE_NAME" -i "$SHARED_DB_SETUP_SCRIPT"

sqlcmd -S "$SQL_SERVER_NAME" -U "$SQL_SERVER_ADMIN_USERNAME" -P "$SQL_SERVER_ADMIN_PASSWORD" -d "$USER_DATABASE_NAME" -i "$USER_DB_SETUP_SCRIPT"
